#!/usr/bin/env python3


import SettingsUnidec
print('----------------------------------------------')
print('  Running assignRun GUI')
print('----------------------------------------------')
print('  (%s version) 14th March 2024            ' % SettingsUnidec.GetVersion())
print('  (c) University of Oxford')
print('----------------------------------------------')
import sys,wx,os
import matplotlib
matplotlib.use('WXAgg')

SettingsUnidec.SetPaths()
import SettingsMAGMA
SettingsMAGMA.SetPaths()


from assign.assign_tab import MyAppAss

if(len(sys.argv)==2):
  deconParFile=sys.argv[1]
else:
   deconParFile='assignParFile'

app = wx.App()
frame = MyAppAss(deconParFile)
app.MainLoop()




